### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by YoYoK3nny**
I made a couple of improvements to ShotcutPortable. It is up to you whether or not the change to CommandLineArguments in ShotcutPortable.ini remains, and the change to appinfo.ini

### CODE REVIEW

**Review by GordCaswell — COMMENTED** [review]
This reminds me that PAL needs support for QtProject alongside Trolltech in the Qt section. Once that's done, and an update to PAL released, this section can be handled with [QtKeysCleanup] rather than with [RegistryKeys].

**Comment by YoYoK3nny** [comment]
Speaking of PAL, what are you're thoughts on Unix-style line ending support for ConfigRead/ConfigWrite? I have a project on hold because such support doesn't exist yet (I did throw together an edit of such support, but haven't tested it yet). Also discovered today that the base app in that project also uses the QtProject key.

**Comment by GordCaswell** [comment]
@yoyokenny , line endings shouldn't matter to ConfigRead/Write. PAL directly implements those from NSIS without any modification whatsoever, so if there's a problem with support, I'd suspect the issue is within NSIS itself, although if that's incorrect, please let me know: http://nsis.sourceforge.net/Docs/AppendixE.html#configread

**Comment by YoYoK3nny** [comment]
They do seem to matter (at least for the app).
The problem is that the config file for the app in question uses unix-style line endings (which are just \n), while the code for ConfigRead/Write expects the Windows-style line endings (which is \r\n).
Initial tests of the PAF'd version of the app did not update paths in the config file due to the different line endings.
The edit I mentioned above is in one of my repos if you'd like to take a look at the unix line ending support that I tried to implement. (Though as yet, I still haven't tested it).

This issue would be better solved though if support for different line endings was implemented within NSIS.

Looking at the code for ConfigRead/Write, it didn't look like it would do the read/write if the \r part wasn't detected.

**Pull request merged**
